### ISSUE TITLE
clarify readme?

### ISSUE THREAD

**Issue by whatSocks** [neo4j-documentation/developer-guides#22]
I'm trying to run this locally, following the instructions I see an error page at 

http://localhost:8000
http://localhost:8000/developer/get-started

```
Cannot GET /developer/get-started
```

readme doesn't specify what version of node or antora I should be on

**Comment by adam-cowley** [comment]
Which command did you run? `npm start`?  It may just be that because you hadn't made any changes the docs wouldn't have built locally for you yet.

The version of antora is specified in package.json so you don't need to worry about it.  Running npm install will be good enough.  

According to the antora docs it requires node version 10 or up, I will update the README to reflect it.

**Comment by whatSocks** [comment]
I followed the steps in the readme, including making a new test adoc and there's no change
